apiVersion: apps/v1
kind: Deployment
metadata:
  name: logmanagement-5gui
  namespace: aether
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logmanagement-5gui
  template:
    metadata:
      labels:
        app: logmanagement-5gui
    spec:
      containers:
      - name: logmanagement-5gui
        image: udhaya21/logmanagement-ui:latest

