apiVersion: v1
kind: Service
metadata:
  name: logmanagement-5gui
  namespace: aether-ui
spec:
  selector:
    app: logmanagement-5gui
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
    nodePort: 30080
  type: NodePort

