apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: 5g-ui-dashboard
  name: 5g-ui-dashboard
spec:
  ports:
  - name: 5g-ui-dashboard
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: 5g-ui-dashboard
  type: NodePort
status:
  loadBalancer: {}
