apiVersion: v1
kind: Service
metadata:
  name: logmanagement-ui
  namespace: aether
spec:
  selector:
    app: logmanagement-ui
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
    nodePort: 30080
  type: NodePort

